### ISSUE TITLE
Please correct the install instructions

### ISSUE THREAD

**Issue by ErisDS** [wrenth04/ghost-imgur#2]
Hi there!

I have just done a review of all the modules that have been linked [here](https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module).

Your install instructions require users to do an `npm install --save` - this modifies the package.json and makes the upgrade path for Ghost much, much harder. This was never the intention with the storage system. 

Instead of `npm install --save`, please update your README and advise people to do the following:

`mkdir content/storage` (make the storage folder if it doesn't exist yet)
`cp node_modules/<module_name> content/storage/<module_name>` (copy the module into the right location)

That makes it much easier to upgrade Ghost in future. 

We are in the process of adding a cli tool that will do these steps automatically, so if your module isn't setup to work this way, it will need to be very soon 😉

**Comment by wrenth04** [comment]
Hi @ErisDS,

I already update README. Thank you for your suggestion.

**Comment by ErisDS** [comment]
Excellent, thank you 👍
