### ISSUE TITLE
Breaking changes in Ghost 0.10.0

### ISSUE THREAD

**Issue by kirrg001** [wrenth04/ghost-imgur#3]
Hey!

We will soon release Ghost `0.10.0` - in about 2 days.
It contains breaking changes for the storage adapter, see https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module.

**Comment by wrenth04** [comment]
I'll update module with Ghost 0.10.0. 
How to setup the module depend?

**Comment by kirrg001** [comment]
For now:

```
var util = require('util');
var BaseStorage = require('../../../core/server/storage/base');

function ghostImgur(config) {
  this.config = config || {};
  BaseStorage.call(this);
}

util.inherits(ghostImgur, BaseStorage);
```

We will improve that in the near future!
You don't have to implement each required function for now -  you can leave them empty!

The background why we started requiring functions for custom adapters is: we move forward in offering the ability to store themes and in the future apps. Your adapter might never store themes, but we would like to offer and test a general validation. 

I can think of having different required function sets for different types of storages (storage only for images, storage only for themes). But we didn't decide yet. 

You can test your adapter with current master. If you have problems or if you find bugs, come over to [slack channel](https://ghost.org/slack/) and i will help you.
